# -----------------------------------------------------------------------------
# Wemos d1 mini + MH-Z19B + CCS811
#
# DATE: 2021-08-22
#
# MH-Z19B use UART on pins:
#   rx_pin: GPIO3
#   tx_pin: GPIO1
#
# CCS811 use i2c on pins:
#   sda: GPIO4
#   scl: GPIO5
#
# Фильтрация значений - при uptime_sensor < 600s не передавать значения сенсоров
#
# -----------------------------------------------------------------------------

esphome:
  name: d1mini-n2
  comment: Датчик качества воздуха в спальне
  platform: ESP8266
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password_n2

# WiFi settings 
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret hotspot_wifi_ssid_n2
    password: !secret hotspot_wifi_password_n1

  reboot_timeout: 30min # время ожидания перед перезагрузкой при отсутствии Wi-Fi-соединения

# Captive portal резервный механизм для настройки, если подключение к сконфигурированной WiFi сети не удалось
captive_portal:

# включим Web server
web_server:
  port: 80
#  auth:
#    username: admin
#    password: !secret web_server_password

# Get the time from Home Assistant to sync the onboard real-time clock.
time:
  - platform: homeassistant
    id: esptime

# СИСТЕМНЫЕ ШИНЫ

# настроим UART
uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600

# настроим i2c
i2c:
  sda: GPIO4
  scl: GPIO5
  scan: true # If ESPHome should do a search of the I2C address space on startup. Defaults to true.

# СЕНСОРЫ
sensor:

  # MH-Z19 CO_2 and Temperature Sensor
  - platform: mhz19
    co2:
      name: "d1mini-n2 MH-Z19 CO2 Value"
      filters:
        - lambda: |-
            if (id(uptime_sensor).state > 600) return x; else return {};
    temperature:
      name: "d1mini-n2 MH-Z19 Temperature"
      filters:
        - lambda: |-
            if (id(uptime_sensor).state > 600) return x; else return {};
    update_interval: 60s
    automatic_baseline_calibration: false

  # CCS811 CO_2 and Volatile Organic Compound Sensor
  - platform: ccs811
    eco2:
      name: "d1mini-n2 CCS811 eCO2 Value"
      filters:
        - lambda: |-
            if (id(uptime_sensor).state > 600) return x; else return {};
    tvoc:
      name: "d1mini-n2 CCS811 Total Volatile Organic Compound"
      filters:
        - lambda: |-
            if (id(uptime_sensor).state > 600) return x; else return {};
    address: 0x5A
    update_interval: 60s

  # Static Calibrating Baseline CCS811
  #- platform: ccs811
  #  baseline: 0xA483

  # системные сенсоры
  - platform: uptime
    name: "d1mini-n2 Uptime Sensor"
    id: uptime_sensor
    update_interval: 60s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? String(days) + "d " : "") +
                (hours ? String(hours) + "h " : "") +
                (minutes ? String(minutes) + "m " : "") +
                (String(seconds) + "s")
              ).c_str();
              
  - platform: wifi_signal
    name: "d1mini-n2 WiFi Signal"
    update_interval: 60s      

# ТЕКСТОВЫЕ СЕНСОРЫ    
text_sensor:
  
  # Версия
  - platform: version
    name: "d1mini-n2 Version"
    
  # Human readable Uptime sensor
  - platform: template
    name: "d1mini-n2 Uptime Human Readable"
    id: uptime_human
    icon: mdi:clock-start

# ПЕРЕКЛЮЧАТЕЛИ
switch:

  # программный переключатель, который позволит нам перезагрузить устройство из Home Assistant (или путем публикации вручную в MQTT или API)
  - platform: restart
    name: "d1mini-n2 restart"
    
